server:
  port: 8001
  servlet:
    context-path: /register

spring:
  application:
    name: leung-eureka-register
  security:
    user:
      name: yves
      password: 186588
  boot:
    admin:
      client:
        # 指定了SBA服务端地址
        url: http://localhost:8401
        # 对应SBA服务端的用户名
        username: yves
        # 对应SBA服务端的密码
        password: 186588

# 配置了SBA客户端的名称，描述和版本信息
info:
  app:
    name: ${spring.application.name}
    description: "Leung-Eureka服务注册中心 register"
    version: "0.0.1-SNAPSHOT"
management:
  endpoints:
    web:
      exposure:
        # 表示将SBA客户端的所有监控端点都暴露给SBA服务端
        include: '*'
  endpoint:
    health:
      # 表示总是展示详细的健康信息
      show-details: ALWAYS

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    instance-info-replication-interval-seconds: 30
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/eureka/